// Code generated by go generate; DO NOT EDIT.

package antoine

var Acetone = &Antoine{
	Name:    "Acetone",
	Formula: "C3H6O",
	A:       14.31450,
	B:       2756.22000,
	C:       228.06000,
	H:       29.10000,
	Range: TempRange{
		Low:  -26.00000,
		High: 77.00000,
	},
	Tn: 56.20000,
}

var AceticAcid = &Antoine{
	Name:    "Acetic acid",
	Formula: "C2H4O",
	A:       215.07170,
	B:       3580.80000,
	C:       224.65000,
	H:       23.70000,
	Range: TempRange{
		Low:  24.00000,
		High: 142.00000,
	},
	Tn: 117.90000,
}

var Acetonitrile = &Antoine{
	Name:    "Acetonitrile",
	Formula: "C2H3N",
	A:       14.89500,
	B:       3413.10000,
	C:       250.52300,
	H:       30.19000,
	Range: TempRange{
		Low:  -27.00000,
		High: 81.00000,
	},
	Tn: 81.60000,
}

var Benzene = &Antoine{
	Name:    "Benzene",
	Formula: "C6H6",
	A:       13.78190,
	B:       2726.81000,
	C:       217.57200,
	H:       30.72000,
	Range: TempRange{
		Low:  6.00000,
		High: 104.00000,
	},
	Tn: 80.00000,
}

var IsoButane = &Antoine{
	Name:    "iso-Butane",
	Formula: "C4H10",
	A:       13.82540,
	B:       2181.79000,
	C:       248.87000,
	H:       21.30000,
	Range: TempRange{
		Low:  -83.00000,
		High: 7.00000,
	},
	Tn: -11.90000,
}

var NButane = &Antoine{
	Name:    "n-Butane",
	Formula: "C4H10",
	A:       13.66080,
	B:       2154.70000,
	C:       238.78900,
	H:       22.44000,
	Range: TempRange{
		Low:  -73.00000,
		High: 19.00000,
	},
	Tn: -0.50000,
}

var OneButanol = &Antoine{
	Name:    "1-Butanol",
	Formula: "C4H10O",
	A:       15.31440,
	B:       3212.43000,
	C:       182.73900,
	H:       43.29000,
	Range: TempRange{
		Low:  37.00000,
		High: 138.00000,
	},
	Tn: 117.60000,
}

var TwoButanol = &Antoine{
	Name:    "2-Butanol",
	Formula: "C4H10O",
	A:       15.19890,
	B:       3026.03000,
	C:       186.50000,
	H:       40.75000,
	Range: TempRange{
		Low:  25.00000,
		High: 120.00000,
	},
	Tn: 99.50000,
}

var IsoButanol = &Antoine{
	Name:    "iso-Butanol",
	Formula: "C4H10O",
	A:       14.60470,
	B:       2740.95000,
	C:       166.67000,
	H:       41.82000,
	Range: TempRange{
		Low:  30.00000,
		High: 128.00000,
	},
	Tn: 107.80000,
}

var TertButanol = &Antoine{
	Name:    "tert-Butanol",
	Formula: "C4H10O",
	A:       14.84450,
	B:       2658.29000,
	C:       177.65000,
	H:       39.07000,
	Range: TempRange{
		Low:  10.00000,
		High: 101.00000,
	},
	Tn: 82.30000,
}

var CarbonTetrachloride = &Antoine{
	Name:    "Carbon tetrachloride",
	Formula: "CCl4",
	A:       14.05720,
	B:       2914.23000,
	C:       232.14800,
	H:       29.82000,
	Range: TempRange{
		Low:  -14.00000,
		High: 101.00000,
	},
	Tn: 76.60000,
}

var Chlorobenzene = &Antoine{
	Name:    "Chlorobenzene",
	Formula: "C6H5Cl",
	A:       13.86350,
	B:       3174.78000,
	C:       211.70000,
	H:       35.19000,
	Range: TempRange{
		Low:  29.00000,
		High: 159.00000,
	},
	Tn: 131.70000,
}

var OneChlorobutane = &Antoine{
	Name:    "1-Chlorobutane",
	Formula: "C4H9Cl",
	A:       13.79650,
	B:       2723.73000,
	C:       218.26500,
	H:       30.39000,
	Range: TempRange{
		Low:  -17.00000,
		High: 79.00000,
	},
	Tn: 78.50000,
}

var Chloroform = &Antoine{
	Name:    "Chloroform",
	Formula: "CHCl3",
	A:       13.73240,
	B:       2548.74000,
	C:       218.55200,
	H:       29.24000,
	Range: TempRange{
		Low:  -23.00000,
		High: 84.00000,
	},
	Tn: 61.10000,
}

var Cyclohexane = &Antoine{
	Name:    "Cyclohexane",
	Formula: "C6H12",
	A:       13.65680,
	B:       2723.44000,
	C:       220.61800,
	H:       29.97000,
	Range: TempRange{
		Low:  9.00000,
		High: 105.00000,
	},
	Tn: 80.70000,
}

var Cyclopentane = &Antoine{
	Name:    "Cyclopentane",
	Formula: "C5H10",
	A:       13.97270,
	B:       2653.90000,
	C:       234.51000,
	H:       27.30000,
	Range: TempRange{
		Low:  -35.00000,
		High: 71.00000,
	},
	Tn: 49.20000,
}

var NDecane = &Antoine{
	Name:    "n-Decane",
	Formula: "C10H22",
	A:       13.97480,
	B:       3442.76000,
	C:       193.85800,
	H:       38.75000,
	Range: TempRange{
		Low:  65.00000,
		High: 203.00000,
	},
	Tn: 174.10000,
}

var Dichloromethane = &Antoine{
	Name:    "Dichloromethane",
	Formula: "CH2Cl",
	A:       213.98910,
	B:       2463.93000,
	C:       223.24000,
	H:       28.06000,
	Range: TempRange{
		Low:  -38.00000,
		High: 60.00000,
	},
	Tn: 39.70000,
}

var DiethylEther = &Antoine{
	Name:    "Diethyl ether",
	Formula: "C4H10O",
	A:       14.07350,
	B:       2511.29000,
	C:       231.20000,
	H:       26.52000,
	Range: TempRange{
		Low:  -43.00000,
		High: 55.00000,
	},
	Tn: 34.40000,
}

var One4Dioxane = &Antoine{
	Name:    "1,4-Dioxane",
	Formula: "C4H8O",
	A:       215.09670,
	B:       3579.78000,
	C:       240.33700,
	H:       34.16000,
	Range: TempRange{
		Low:  20.00000,
		High: 105.00000,
	},
	Tn: 101.30000,
}

var NEicosane = &Antoine{
	Name:    "n-Eicosane",
	Formula: "C20H42",
	A:       14.45750,
	B:       4680.46000,
	C:       132.10000,
	H:       57.49000,
	Range: TempRange{
		Low:  208.00000,
		High: 379.00000,
	},
	Tn: 343.60000,
}

var Ethanol = &Antoine{
	Name:    "Ethanol",
	Formula: "C2H6O",
	A:       16.89580,
	B:       3795.17000,
	C:       230.91800,
	H:       38.56000,
	Range: TempRange{
		Low:  3.00000,
		High: 96.00000,
	},
	Tn: 78.20000,
}

var Ethylbenzene = &Antoine{
	Name:    "Ethylbenzene",
	Formula: "C8H10",
	A:       13.97260,
	B:       3259.93000,
	C:       212.30000,
	H:       35.57000,
	Range: TempRange{
		Low:  33.00000,
		High: 163.00000,
	},
	Tn: 136.20000,
}

var EthyleneGlycol = &Antoine{
	Name:    "Ethylene glycol",
	Formula: "C2H6O",
	A:       215.75670,
	B:       4187.46000,
	C:       178.65000,
	H:       50.73000,
	Range: TempRange{
		Low:  100.00000,
		High: 222.00000,
	},
	Tn: 197.30000,
}

var NHeptane = &Antoine{
	Name:    "n-Heptane",
	Formula: "C7H16",
	A:       13.86220,
	B:       2910.26000,
	C:       216.43200,
	H:       31.77000,
	Range: TempRange{
		Low:  4.00000,
		High: 123.00000,
	},
	Tn: 98.40000,
}

var NHexane = &Antoine{
	Name:    "n-Hexane",
	Formula: "C6H14",
	A:       13.81930,
	B:       2696.04000,
	C:       224.31700,
	H:       28.85000,
	Range: TempRange{
		Low:  -19.00000,
		High: 92.00000,
	},
	Tn: 68.70000,
}

var Methanol = &Antoine{
	Name:    "Methanol",
	Formula: "CH4O",
	A:       16.57850,
	B:       3638.27000,
	C:       239.50000,
	H:       35.21000,
	Range: TempRange{
		Low:  -11.00000,
		High: 83.00000,
	},
	Tn: 64.70000,
}

var MethylAcetate = &Antoine{
	Name:    "Methyl acetate",
	Formula: "C3H6O",
	A:       214.24560,
	B:       2662.78000,
	C:       219.69000,
	H:       30.32000,
	Range: TempRange{
		Low:  -23.00000,
		High: 78.00000,
	},
	Tn: 56.90000,
}

var MethylEthylKetone = &Antoine{
	Name:    "Methyl ethyl ketone",
	Formula: "C4H8O",
	A:       14.13340,
	B:       2838.24000,
	C:       218.69000,
	H:       31.30000,
	Range: TempRange{
		Low:  -8.00000,
		High: 103.00000,
	},
	Tn: 79.60000,
}

var Nitromethane = &Antoine{
	Name:    "Nitromethane",
	Formula: "CH3NO",
	A:       214.75130,
	B:       3331.70000,
	C:       227.60000,
	H:       33.99000,
	Range: TempRange{
		Low:  56.00000,
		High: 146.00000,
	},
	Tn: 101.20000,
}

var NNonane = &Antoine{
	Name:    "n-Nonane",
	Formula: "C9H20",
	A:       13.98540,
	B:       3311.19000,
	C:       202.69400,
	H:       36.91000,
	Range: TempRange{
		Low:  46.00000,
		High: 178.00000,
	},
	Tn: 150.80000,
}

var IsoOctane = &Antoine{
	Name:    "iso-Octane",
	Formula: "C8H18",
	A:       13.67030,
	B:       2896.31000,
	C:       220.76700,
	H:       30.79000,
	Range: TempRange{
		Low:  2.00000,
		High: 125.00000,
	},
	Tn: 99.20000,
}

var NOctane = &Antoine{
	Name:    "n-Octane",
	Formula: "C8H18",
	A:       13.93460,
	B:       3123.13000,
	C:       209.63500,
	H:       34.41000,
	Range: TempRange{
		Low:  26.00000,
		High: 152.00000,
	},
	Tn: 125.60000,
}

var NPentane = &Antoine{
	Name:    "n-Pentane",
	Formula: "C5H12",
	A:       13.76670,
	B:       2451.88000,
	C:       232.01400,
	H:       25.79000,
	Range: TempRange{
		Low:  -45.00000,
		High: 58.00000,
	},
	Tn: 36.00000,
}

var Phenol = &Antoine{
	Name:    "Phenol",
	Formula: "C6H6O",
	A:       14.43870,
	B:       3507.80000,
	C:       175.40000,
	H:       46.18000,
	Range: TempRange{
		Low:  80.00000,
		High: 208.00000,
	},
	Tn: 181.80000,
}

var OnePropanol = &Antoine{
	Name:    "1-Propanol",
	Formula: "C3H8O",
	A:       16.11540,
	B:       3483.67000,
	C:       205.80700,
	H:       41.44000,
	Range: TempRange{
		Low:  20.00000,
		High: 116.00000,
	},
	Tn: 97.20000,
}

var TwoPropanol = &Antoine{
	Name:    "2-Propanol",
	Formula: "C3H8O",
	A:       16.67960,
	B:       3640.20000,
	C:       219.61000,
	H:       39.85000,
	Range: TempRange{
		Low:  8.00000,
		High: 100.00000,
	},
	Tn: 82.20000,
}

var Toluene = &Antoine{
	Name:    "Toluene",
	Formula: "C7H8",
	A:       13.93200,
	B:       3056.96000,
	C:       217.62500,
	H:       33.18000,
	Range: TempRange{
		Low:  13.00000,
		High: 136.00000,
	},
	Tn: 110.60000,
}

var Water = &Antoine{
	Name:    "Water",
	Formula: "H2O",
	A:       16.38720,
	B:       3885.70000,
	C:       230.17000,
	H:       40.66000,
	Range: TempRange{
		Low:  0.00000,
		High: 200.00000,
	},
	Tn: 100.00000,
}

var OXylene = &Antoine{
	Name:    "o-Xylene",
	Formula: "C8H10",
	A:       14.04150,
	B:       3358.79000,
	C:       212.04100,
	H:       36.24000,
	Range: TempRange{
		Low:  40.00000,
		High: 172.00000,
	},
	Tn: 144.40000,
}

var MXylene = &Antoine{
	Name:    "m-Xylene",
	Formula: "C8H10",
	A:       14.13870,
	B:       3381.81000,
	C:       216.12000,
	H:       35.66000,
	Range: TempRange{
		Low:  35.00000,
		High: 166.00000,
	},
	Tn: 139.10000,
}

var PXylene = &Antoine{
	Name:    "p-Xylene",
	Formula: "C8H10",
	A:       14.05790,
	B:       3331.45000,
	C:       214.62700,
	H:       35.67000,
	Range: TempRange{
		Low:  35.00000,
		High: 166.00000,
	},
	Tn: 138.30000,
}
