// Code generated by go generate; DO NOT EDIT.

package substance

var Methane = Substance{
	Name:     "Methane",
	MW:       16.04300,
	Acentric: 0.01200,
	Tn:       111.40000,
	Critical: CriticalProps{
		Tc: 190.60000,
		Pc: 45.99000,
		Vc: 98.60000,
		Zc: 0.28600,
	},
}

var Ethane = Substance{
	Name:     "Ethane",
	MW:       30.07000,
	Acentric: 0.10000,
	Tn:       184.60000,
	Critical: CriticalProps{
		Tc: 305.30000,
		Pc: 48.72000,
		Vc: 145.50000,
		Zc: 0.27900,
	},
}

var Propane = Substance{
	Name:     "Propane",
	MW:       44.09700,
	Acentric: 0.15200,
	Tn:       231.10000,
	Critical: CriticalProps{
		Tc: 369.80000,
		Pc: 42.48000,
		Vc: 200.00000,
		Zc: 0.27600,
	},
}

var NButane = Substance{
	Name:     "n-Butane",
	MW:       58.12300,
	Acentric: 0.20000,
	Tn:       272.70000,
	Critical: CriticalProps{
		Tc: 425.10000,
		Pc: 37.96000,
		Vc: 255.00000,
		Zc: 0.27400,
	},
}

var NPentane = Substance{
	Name:     "n-Pentane",
	MW:       72.15000,
	Acentric: 0.25200,
	Tn:       309.20000,
	Critical: CriticalProps{
		Tc: 469.70000,
		Pc: 33.70000,
		Vc: 313.00000,
		Zc: 0.27000,
	},
}

var NHexane = Substance{
	Name:     "n-Hexane",
	MW:       86.17700,
	Acentric: 0.30100,
	Tn:       341.90000,
	Critical: CriticalProps{
		Tc: 507.60000,
		Pc: 30.25000,
		Vc: 371.00000,
		Zc: 0.26600,
	},
}

var NHeptane = Substance{
	Name:     "n-Heptane",
	MW:       100.20400,
	Acentric: 0.35000,
	Tn:       371.60000,
	Critical: CriticalProps{
		Tc: 540.20000,
		Pc: 27.40000,
		Vc: 428.00000,
		Zc: 0.26100,
	},
}

var NOctane = Substance{
	Name:     "n-Octane",
	MW:       114.23100,
	Acentric: 0.40000,
	Tn:       398.80000,
	Critical: CriticalProps{
		Tc: 568.70000,
		Pc: 24.90000,
		Vc: 486.00000,
		Zc: 0.25600,
	},
}

var NNonane = Substance{
	Name:     "n-Nonane",
	MW:       128.25800,
	Acentric: 0.44400,
	Tn:       424.00000,
	Critical: CriticalProps{
		Tc: 594.60000,
		Pc: 22.90000,
		Vc: 544.00000,
		Zc: 0.25200,
	},
}

var NDecane = Substance{
	Name:     "n-Decane",
	MW:       142.28500,
	Acentric: 0.49200,
	Tn:       447.30000,
	Critical: CriticalProps{
		Tc: 617.70000,
		Pc: 21.10000,
		Vc: 600.00000,
		Zc: 0.24700,
	},
}

var Isobutane = Substance{
	Name:     "Isobutane",
	MW:       58.12300,
	Acentric: 0.18100,
	Tn:       261.40000,
	Critical: CriticalProps{
		Tc: 408.10000,
		Pc: 36.48000,
		Vc: 262.70000,
		Zc: 0.28200,
	},
}

var Cyclopentane = Substance{
	Name:     "Cyclopentane",
	MW:       70.13400,
	Acentric: 0.19600,
	Tn:       322.40000,
	Critical: CriticalProps{
		Tc: 511.80000,
		Pc: 45.02000,
		Vc: 258.00000,
		Zc: 0.27300,
	},
}

var Cyclohexane = Substance{
	Name:     "Cyclohexane",
	MW:       84.16100,
	Acentric: 0.21000,
	Tn:       353.90000,
	Critical: CriticalProps{
		Tc: 553.60000,
		Pc: 40.73000,
		Vc: 308.00000,
		Zc: 0.27300,
	},
}

var Methylcyclopentane = Substance{
	Name:     "Methylcyclopentane",
	MW:       84.16100,
	Acentric: 0.23000,
	Tn:       345.00000,
	Critical: CriticalProps{
		Tc: 532.80000,
		Pc: 37.85000,
		Vc: 319.00000,
		Zc: 0.27200,
	},
}

var Methylcyclohexane = Substance{
	Name:     "Methylcyclohexane",
	MW:       98.18800,
	Acentric: 0.23500,
	Tn:       374.10000,
	Critical: CriticalProps{
		Tc: 572.20000,
		Pc: 34.71000,
		Vc: 368.00000,
		Zc: 0.26900,
	},
}

var Ethylene = Substance{
	Name:     "Ethylene",
	MW:       28.05400,
	Acentric: 0.08700,
	Tn:       169.40000,
	Critical: CriticalProps{
		Tc: 282.30000,
		Pc: 50.40000,
		Vc: 131.00000,
		Zc: 0.28100,
	},
}

var Propylene = Substance{
	Name:     "Propylene",
	MW:       42.08100,
	Acentric: 0.14000,
	Tn:       225.50000,
	Critical: CriticalProps{
		Tc: 365.60000,
		Pc: 46.65000,
		Vc: 188.40000,
		Zc: 0.28900,
	},
}

var OneButene = Substance{
	Name:     "1-Butene",
	MW:       56.10800,
	Acentric: 0.19100,
	Tn:       266.90000,
	Critical: CriticalProps{
		Tc: 420.00000,
		Pc: 40.43000,
		Vc: 239.30000,
		Zc: 0.27700,
	},
}

var Cis2Butene = Substance{
	Name:     "cis-2-Butene",
	MW:       56.10800,
	Acentric: 0.20500,
	Tn:       276.90000,
	Critical: CriticalProps{
		Tc: 435.60000,
		Pc: 42.43000,
		Vc: 233.80000,
		Zc: 0.27300,
	},
}

var Trans2Butene = Substance{
	Name:     "trans -2-Butene",
	MW:       56.10800,
	Acentric: 0.21800,
	Tn:       274.00000,
	Critical: CriticalProps{
		Tc: 428.60000,
		Pc: 41.00000,
		Vc: 237.70000,
		Zc: 0.27500,
	},
}

var OneHexene = Substance{
	Name:     "1-Hexene",
	MW:       84.16100,
	Acentric: 0.28000,
	Tn:       336.30000,
	Critical: CriticalProps{
		Tc: 504.00000,
		Pc: 31.40000,
		Vc: 354.00000,
		Zc: 0.26500,
	},
}

var Isobutylene = Substance{
	Name:     "Isobutylene",
	MW:       56.10800,
	Acentric: 0.19400,
	Tn:       266.30000,
	Critical: CriticalProps{
		Tc: 417.90000,
		Pc: 40.00000,
		Vc: 238.90000,
		Zc: 0.27500,
	},
}

var One3Butadiene = Substance{
	Name:     "1,3-Butadiene",
	MW:       54.09200,
	Acentric: 0.19000,
	Tn:       268.70000,
	Critical: CriticalProps{
		Tc: 425.20000,
		Pc: 42.77000,
		Vc: 220.40000,
		Zc: 0.26700,
	},
}

var Cyclohexene = Substance{
	Name:     "Cyclohexene",
	MW:       82.14500,
	Acentric: 0.21200,
	Tn:       356.10000,
	Critical: CriticalProps{
		Tc: 560.40000,
		Pc: 43.50000,
		Vc: 291.00000,
		Zc: 0.27200,
	},
}

var Acetylene = Substance{
	Name:     "Acetylene",
	MW:       26.03800,
	Acentric: 0.18700,
	Tn:       189.40000,
	Critical: CriticalProps{
		Tc: 308.30000,
		Pc: 61.39000,
		Vc: 113.00000,
		Zc: 0.27100,
	},
}

var Benzene = Substance{
	Name:     "Benzene",
	MW:       78.11400,
	Acentric: 0.21000,
	Tn:       353.20000,
	Critical: CriticalProps{
		Tc: 562.20000,
		Pc: 48.98000,
		Vc: 259.00000,
		Zc: 0.27100,
	},
}

var Toluene = Substance{
	Name:     "Toluene",
	MW:       92.14100,
	Acentric: 0.26200,
	Tn:       383.80000,
	Critical: CriticalProps{
		Tc: 591.80000,
		Pc: 41.06000,
		Vc: 316.00000,
		Zc: 0.26400,
	},
}

var Ethylbenzene = Substance{
	Name:     "Ethylbenzene",
	MW:       106.16700,
	Acentric: 0.30300,
	Tn:       409.40000,
	Critical: CriticalProps{
		Tc: 617.20000,
		Pc: 36.06000,
		Vc: 374.00000,
		Zc: 0.26300,
	},
}

var Cumene = Substance{
	Name:     "Cumene",
	MW:       120.19400,
	Acentric: 0.32600,
	Tn:       425.60000,
	Critical: CriticalProps{
		Tc: 631.10000,
		Pc: 32.09000,
		Vc: 427.00000,
		Zc: 0.26100,
	},
}

var OXylene = Substance{
	Name:     "o-Xylene",
	MW:       106.16700,
	Acentric: 0.31000,
	Tn:       417.60000,
	Critical: CriticalProps{
		Tc: 630.30000,
		Pc: 37.34000,
		Vc: 369.00000,
		Zc: 0.26300,
	},
}

var MXylene = Substance{
	Name:     "m-Xylene",
	MW:       106.16700,
	Acentric: 0.32600,
	Tn:       412.30000,
	Critical: CriticalProps{
		Tc: 617.10000,
		Pc: 35.36000,
		Vc: 376.00000,
		Zc: 0.25900,
	},
}

var PXylene = Substance{
	Name:     "p-Xylene",
	MW:       106.16700,
	Acentric: 0.32200,
	Tn:       411.50000,
	Critical: CriticalProps{
		Tc: 616.20000,
		Pc: 35.11000,
		Vc: 379.00000,
		Zc: 0.26000,
	},
}

var Styrene = Substance{
	Name:     "Styrene",
	MW:       104.15200,
	Acentric: 0.29700,
	Tn:       418.30000,
	Critical: CriticalProps{
		Tc: 636.00000,
		Pc: 38.40000,
		Vc: 352.00000,
		Zc: 0.25600,
	},
}

var Naphthalene = Substance{
	Name:     "Naphthalene",
	MW:       128.17400,
	Acentric: 0.30200,
	Tn:       491.20000,
	Critical: CriticalProps{
		Tc: 748.40000,
		Pc: 40.51000,
		Vc: 413.00000,
		Zc: 0.26900,
	},
}

var Biphenyl = Substance{
	Name:     "Biphenyl",
	MW:       154.21100,
	Acentric: 0.36500,
	Tn:       528.20000,
	Critical: CriticalProps{
		Tc: 789.30000,
		Pc: 38.50000,
		Vc: 502.00000,
		Zc: 0.29500,
	},
}

var Formaldehyde = Substance{
	Name:     "Formaldehyde",
	MW:       30.02600,
	Acentric: 0.28200,
	Tn:       254.10000,
	Critical: CriticalProps{
		Tc: 408.00000,
		Pc: 65.90000,
		Vc: 115.00000,
		Zc: 0.22300,
	},
}

var Acetaldehyde = Substance{
	Name:     "Acetaldehyde",
	MW:       44.05300,
	Acentric: 0.29100,
	Tn:       294.00000,
	Critical: CriticalProps{
		Tc: 466.00000,
		Pc: 55.50000,
		Vc: 154.00000,
		Zc: 0.22100,
	},
}

var MethylAcetate = Substance{
	Name:     "Methyl acetate",
	MW:       74.07900,
	Acentric: 0.33100,
	Tn:       330.10000,
	Critical: CriticalProps{
		Tc: 506.60000,
		Pc: 47.50000,
		Vc: 228.00000,
		Zc: 0.25700,
	},
}

var EthylAcetate = Substance{
	Name:     "Ethyl acetate",
	MW:       88.10600,
	Acentric: 0.36600,
	Tn:       350.20000,
	Critical: CriticalProps{
		Tc: 523.30000,
		Pc: 38.80000,
		Vc: 286.00000,
		Zc: 0.25500,
	},
}

var Acetone = Substance{
	Name:     "Acetone",
	MW:       58.08000,
	Acentric: 0.30700,
	Tn:       329.40000,
	Critical: CriticalProps{
		Tc: 508.20000,
		Pc: 47.01000,
		Vc: 209.00000,
		Zc: 0.23300,
	},
}

var MethylEthylKetone = Substance{
	Name:     "Methyl ethyl ketone",
	MW:       72.10700,
	Acentric: 0.32300,
	Tn:       352.80000,
	Critical: CriticalProps{
		Tc: 535.50000,
		Pc: 41.50000,
		Vc: 267.00000,
		Zc: 0.24900,
	},
}

var DiethylEther = Substance{
	Name:     "Diethyl ether",
	MW:       74.12300,
	Acentric: 0.28100,
	Tn:       307.60000,
	Critical: CriticalProps{
		Tc: 466.70000,
		Pc: 36.40000,
		Vc: 280.00000,
		Zc: 0.26300,
	},
}

var MethylTButylEther = Substance{
	Name:     "Methyl t-butyl ether",
	MW:       88.15000,
	Acentric: 0.26600,
	Tn:       328.40000,
	Critical: CriticalProps{
		Tc: 497.10000,
		Pc: 34.30000,
		Vc: 329.00000,
		Zc: 0.27300,
	},
}

var Methanol = Substance{
	Name:     "Methanol",
	MW:       32.04200,
	Acentric: 0.56400,
	Tn:       337.90000,
	Critical: CriticalProps{
		Tc: 512.60000,
		Pc: 80.97000,
		Vc: 118.00000,
		Zc: 0.22400,
	},
}

var Ethanol = Substance{
	Name:     "Ethanol",
	MW:       46.06900,
	Acentric: 0.64500,
	Tn:       351.40000,
	Critical: CriticalProps{
		Tc: 513.90000,
		Pc: 61.48000,
		Vc: 167.00000,
		Zc: 0.24000,
	},
}

var OnePropanol = Substance{
	Name:     "1-Propanol",
	MW:       60.09600,
	Acentric: 0.62200,
	Tn:       370.40000,
	Critical: CriticalProps{
		Tc: 536.80000,
		Pc: 51.75000,
		Vc: 219.00000,
		Zc: 0.25400,
	},
}

var OneButanol = Substance{
	Name:     "1-Butanol",
	MW:       74.12300,
	Acentric: 0.59400,
	Tn:       390.80000,
	Critical: CriticalProps{
		Tc: 563.10000,
		Pc: 44.23000,
		Vc: 275.00000,
		Zc: 0.26000,
	},
}

var OneHexanol = Substance{
	Name:     "1-Hexanol",
	MW:       102.17700,
	Acentric: 0.57900,
	Tn:       430.60000,
	Critical: CriticalProps{
		Tc: 611.40000,
		Pc: 35.10000,
		Vc: 381.00000,
		Zc: 0.26300,
	},
}

var TwoPropanol = Substance{
	Name:     "2-Propanol",
	MW:       60.09600,
	Acentric: 0.66800,
	Tn:       355.40000,
	Critical: CriticalProps{
		Tc: 508.30000,
		Pc: 47.62000,
		Vc: 220.00000,
		Zc: 0.24800,
	},
}

var EthyleneGlycol = Substance{
	Name:     "Ethylene glycol",
	MW:       62.06800,
	Acentric: 0.48700,
	Tn:       470.50000,
	Critical: CriticalProps{
		Tc: 719.70000,
		Pc: 77.00000,
		Vc: 191.00000,
		Zc: 0.24600,
	},
}

var AceticAcid = Substance{
	Name:     "Acetic acid",
	MW:       60.05300,
	Acentric: 0.46700,
	Tn:       391.10000,
	Critical: CriticalProps{
		Tc: 592.00000,
		Pc: 57.86000,
		Vc: 179.70000,
		Zc: 0.21100,
	},
}

var NButyricAcid = Substance{
	Name:     "n-Butyric acid",
	MW:       88.10600,
	Acentric: 0.68100,
	Tn:       436.40000,
	Critical: CriticalProps{
		Tc: 615.70000,
		Pc: 40.64000,
		Vc: 291.70000,
		Zc: 0.23200,
	},
}

var BenzoicAcid = Substance{
	Name:     "Benzoic acid",
	MW:       122.12300,
	Acentric: 0.60300,
	Tn:       522.40000,
	Critical: CriticalProps{
		Tc: 751.00000,
		Pc: 44.70000,
		Vc: 344.00000,
		Zc: 0.24600,
	},
}

var Acetonitrile = Substance{
	Name:     "Acetonitrile",
	MW:       41.05300,
	Acentric: 0.33800,
	Tn:       354.80000,
	Critical: CriticalProps{
		Tc: 545.50000,
		Pc: 48.30000,
		Vc: 173.00000,
		Zc: 0.18400,
	},
}

var Methylamine = Substance{
	Name:     "Methylamine",
	MW:       31.05700,
	Acentric: 0.28100,
	Tn:       266.80000,
	Critical: CriticalProps{
		Tc: 430.10000,
		Pc: 74.60000,
		Vc: 154.00000,
		Zc: 0.32100,
	},
}

var Ethylamine = Substance{
	Name:     "Ethylamine",
	MW:       45.08400,
	Acentric: 0.28500,
	Tn:       289.70000,
	Critical: CriticalProps{
		Tc: 456.20000,
		Pc: 56.20000,
		Vc: 207.00000,
		Zc: 0.30700,
	},
}

var Nitromethane = Substance{
	Name:     "Nitromethane",
	MW:       61.04000,
	Acentric: 0.34800,
	Tn:       374.40000,
	Critical: CriticalProps{
		Tc: 588.20000,
		Pc: 63.10000,
		Vc: 173.00000,
		Zc: 0.22300,
	},
}

var CarbonTetrachloride = Substance{
	Name:     "Carbon tetrachloride",
	MW:       153.82200,
	Acentric: 0.19300,
	Tn:       349.80000,
	Critical: CriticalProps{
		Tc: 556.40000,
		Pc: 45.60000,
		Vc: 276.00000,
		Zc: 0.27200,
	},
}

var Chloroform = Substance{
	Name:     "Chloroform",
	MW:       119.37700,
	Acentric: 0.22200,
	Tn:       334.30000,
	Critical: CriticalProps{
		Tc: 536.40000,
		Pc: 54.72000,
		Vc: 239.00000,
		Zc: 0.29300,
	},
}

var Dichloromethane = Substance{
	Name:     "Dichloromethane",
	MW:       84.93200,
	Acentric: 0.19900,
	Tn:       312.90000,
	Critical: CriticalProps{
		Tc: 510.00000,
		Pc: 60.80000,
		Vc: 185.00000,
		Zc: 0.26500,
	},
}

var MethylChloride = Substance{
	Name:     "Methyl chloride",
	MW:       50.48800,
	Acentric: 0.15300,
	Tn:       249.10000,
	Critical: CriticalProps{
		Tc: 416.30000,
		Pc: 66.80000,
		Vc: 143.00000,
		Zc: 0.27600,
	},
}

var EthylChloride = Substance{
	Name:     "Ethyl chloride",
	MW:       64.51400,
	Acentric: 0.19000,
	Tn:       285.40000,
	Critical: CriticalProps{
		Tc: 460.40000,
		Pc: 52.70000,
		Vc: 200.00000,
		Zc: 0.27500,
	},
}

var Chlorobenzene = Substance{
	Name:     "Chlorobenzene",
	MW:       112.55800,
	Acentric: 0.25000,
	Tn:       404.90000,
	Critical: CriticalProps{
		Tc: 632.40000,
		Pc: 45.20000,
		Vc: 308.00000,
		Zc: 0.26500,
	},
}

var Tetrafluoroethane = Substance{
	Name:     "Tetrafluoroethane",
	MW:       102.03000,
	Acentric: 0.32700,
	Tn:       247.10000,
	Critical: CriticalProps{
		Tc: 374.20000,
		Pc: 40.60000,
		Vc: 198.00000,
		Zc: 0.25800,
	},
}

var Argon = Substance{
	Name:     "Argon",
	MW:       39.94800,
	Acentric: 0.00000,
	Tn:       87.30000,
	Critical: CriticalProps{
		Tc: 150.90000,
		Pc: 48.98000,
		Vc: 74.60000,
		Zc: 0.29100,
	},
}

var Krypton = Substance{
	Name:     "Krypton",
	MW:       83.80000,
	Acentric: 0.00000,
	Tn:       119.80000,
	Critical: CriticalProps{
		Tc: 209.40000,
		Pc: 55.02000,
		Vc: 91.20000,
		Zc: 0.28800,
	},
}

var Xenon = Substance{
	Name:     "Xenon",
	MW:       131.30000,
	Acentric: 0.00000,
	Tn:       165.00000,
	Critical: CriticalProps{
		Tc: 289.70000,
		Pc: 58.40000,
		Vc: 118.00000,
		Zc: 0.28600,
	},
}

var Helium4 = Substance{
	Name:     "Helium 4",
	MW:       4.00300,
	Acentric: 0.39000,
	Tn:       4.20000,
	Critical: CriticalProps{
		Tc: 5.20000,
		Pc: 2.28000,
		Vc: 57.30000,
		Zc: 0.30200,
	},
}

var Hydrogen = Substance{
	Name:     "Hydrogen",
	MW:       2.01600,
	Acentric: 0.21600,
	Tn:       20.40000,
	Critical: CriticalProps{
		Tc: 33.19000,
		Pc: 13.13000,
		Vc: 64.10000,
		Zc: 0.30500,
	},
}

var Oxygen = Substance{
	Name:     "Oxygen",
	MW:       31.99900,
	Acentric: 0.02200,
	Tn:       90.20000,
	Critical: CriticalProps{
		Tc: 154.60000,
		Pc: 50.43000,
		Vc: 73.40000,
		Zc: 0.28800,
	},
}

var Nitrogen = Substance{
	Name:     "Nitrogen",
	MW:       28.01400,
	Acentric: 0.03800,
	Tn:       77.30000,
	Critical: CriticalProps{
		Tc: 126.20000,
		Pc: 34.00000,
		Vc: 89.20000,
		Zc: 0.28900,
	},
}

var Chlorine = Substance{
	Name:     "Chlorine",
	MW:       70.90500,
	Acentric: 0.06900,
	Tn:       239.10000,
	Critical: CriticalProps{
		Tc: 417.20000,
		Pc: 77.10000,
		Vc: 124.00000,
		Zc: 0.26500,
	},
}

var CarbonMonoxide = Substance{
	Name:     "Carbon monoxide",
	MW:       28.01000,
	Acentric: 0.04800,
	Tn:       81.70000,
	Critical: CriticalProps{
		Tc: 132.90000,
		Pc: 34.99000,
		Vc: 93.40000,
		Zc: 0.29900,
	},
}

var CarbonDisulfide = Substance{
	Name:     "Carbon disulfide",
	MW:       76.14300,
	Acentric: 0.11100,
	Tn:       319.40000,
	Critical: CriticalProps{
		Tc: 552.00000,
		Pc: 79.00000,
		Vc: 160.00000,
		Zc: 0.27500,
	},
}

var HydrogenSulfide = Substance{
	Name:     "Hydrogen sulfide",
	MW:       34.08200,
	Acentric: 0.09400,
	Tn:       212.80000,
	Critical: CriticalProps{
		Tc: 373.50000,
		Pc: 89.63000,
		Vc: 98.50000,
		Zc: 0.28400,
	},
}

var SulfurDioxide = Substance{
	Name:     "Sulfur dioxide",
	MW:       64.06500,
	Acentric: 0.24500,
	Tn:       263.10000,
	Critical: CriticalProps{
		Tc: 430.80000,
		Pc: 78.84000,
		Vc: 122.00000,
		Zc: 0.26900,
	},
}

var SulfurTrioxide = Substance{
	Name:     "Sulfur trioxide",
	MW:       80.06400,
	Acentric: 0.42400,
	Tn:       317.90000,
	Critical: CriticalProps{
		Tc: 490.90000,
		Pc: 82.10000,
		Vc: 127.00000,
		Zc: 0.25500,
	},
}

var NitricOxide = Substance{
	Name:     "Nitric oxide (NO)",
	MW:       30.00600,
	Acentric: 0.58300,
	Tn:       121.40000,
	Critical: CriticalProps{
		Tc: 180.20000,
		Pc: 64.80000,
		Vc: 58.00000,
		Zc: 0.25100,
	},
}

var NitrousOxide = Substance{
	Name:     "Nitrous oxide (N 2O)",
	MW:       44.01300,
	Acentric: 0.14100,
	Tn:       184.70000,
	Critical: CriticalProps{
		Tc: 309.60000,
		Pc: 72.45000,
		Vc: 97.40000,
		Zc: 0.27400,
	},
}

var HydrogenChloride = Substance{
	Name:     "Hydrogen chloride",
	MW:       36.46100,
	Acentric: 0.13200,
	Tn:       188.20000,
	Critical: CriticalProps{
		Tc: 324.70000,
		Pc: 83.10000,
		Vc: 81.00000,
		Zc: 0.24900,
	},
}

var HydrogenCyanide = Substance{
	Name:     "Hydrogen cyanide",
	MW:       27.02600,
	Acentric: 0.41000,
	Tn:       298.90000,
	Critical: CriticalProps{
		Tc: 456.70000,
		Pc: 53.90000,
		Vc: 139.00000,
		Zc: 0.19700,
	},
}

var Water = Substance{
	Name:     "Water",
	MW:       18.01500,
	Acentric: 0.34500,
	Tn:       373.20000,
	Critical: CriticalProps{
		Tc: 647.10000,
		Pc: 220.55000,
		Vc: 55.90000,
		Zc: 0.22900,
	},
}

var Ammonia = Substance{
	Name:     "Ammonia",
	MW:       17.03100,
	Acentric: 0.25300,
	Tn:       239.70000,
	Critical: CriticalProps{
		Tc: 405.70000,
		Pc: 112.80000,
		Vc: 72.50000,
		Zc: 0.24200,
	},
}

var NitricAcid = Substance{
	Name:     "Nitric acid",
	MW:       63.01300,
	Acentric: 0.71400,
	Tn:       356.20000,
	Critical: CriticalProps{
		Tc: 520.00000,
		Pc: 68.90000,
		Vc: 145.00000,
		Zc: 0.23100,
	},
}

var SulfuricAcid = Substance{
	Name:     "Sulfuric acid",
	MW:       98.08000,
	Acentric: 0.00000,
	Tn:       610.00000,
	Critical: CriticalProps{
		Tc: 924.00000,
		Pc: 64.00000,
		Vc: 177.00000,
		Zc: 0.14700,
	},
}
