// Code generated by go generate; DO NOT EDIT.

package cp

var MethaneGas = &HeatCapacity{
	Name:    "Methane",
	Formula: "CH4",
	TMin:    298.15,
	TMax:    1500,
	Cp298:   4.217,
	A:       1.702,
	B:       9.081 * 1e-3,
	C:       -2.164 * 1e-6,
	D:       0 * 1e5,
}

var EthaneGas = &HeatCapacity{
	Name:    "Ethane",
	Formula: "C2H6",
	TMin:    298.15,
	TMax:    1500,
	Cp298:   6.369,
	A:       1.131,
	B:       19.225 * 1e-3,
	C:       -5.561 * 1e-6,
	D:       0 * 1e5,
}

var PropaneGas = &HeatCapacity{
	Name:    "Propane",
	Formula: "C3H8",
	TMin:    298.15,
	TMax:    1500,
	Cp298:   9.011,
	A:       1.213,
	B:       28.785 * 1e-3,
	C:       -8.824 * 1e-6,
	D:       0 * 1e5,
}

var NButaneGas = &HeatCapacity{
	Name:    "n-Butane",
	Formula: "C4H10",
	TMin:    298.15,
	TMax:    1500,
	Cp298:   11.928,
	A:       1.935,
	B:       36.915 * 1e-3,
	C:       -11.402 * 1e-6,
	D:       0 * 1e5,
}

var IsoButaneGas = &HeatCapacity{
	Name:    "iso-Butane",
	Formula: "C4H10",
	TMin:    298.15,
	TMax:    1500,
	Cp298:   11.901,
	A:       1.677,
	B:       37.853 * 1e-3,
	C:       -11.945 * 1e-6,
	D:       0 * 1e5,
}

var NPentaneGas = &HeatCapacity{
	Name:    "n-Pentane",
	Formula: "C5H12",
	TMin:    298.15,
	TMax:    1500,
	Cp298:   14.731,
	A:       2.464,
	B:       45.351 * 1e-3,
	C:       -14.111 * 1e-6,
	D:       0 * 1e5,
}

var NHexaneGas = &HeatCapacity{
	Name:    "n-Hexane",
	Formula: "C6H14",
	TMin:    298.15,
	TMax:    1500,
	Cp298:   17.55,
	A:       3.025,
	B:       53.722 * 1e-3,
	C:       -16.791 * 1e-6,
	D:       0 * 1e5,
}

var NHeptaneGas = &HeatCapacity{
	Name:    "n-Heptane",
	Formula: "C7H16",
	TMin:    298.15,
	TMax:    1500,
	Cp298:   20.361,
	A:       3.57,
	B:       62.127 * 1e-3,
	C:       -19.486 * 1e-6,
	D:       0 * 1e5,
}

var NOctaneGas = &HeatCapacity{
	Name:    "n-Octane",
	Formula: "C8H18",
	TMin:    298.15,
	TMax:    1500,
	Cp298:   23.174,
	A:       4.108,
	B:       70.567 * 1e-3,
	C:       -22.208 * 1e-6,
	D:       0 * 1e5,
}

var EthyleneGas = &HeatCapacity{
	Name:    "Ethylene",
	Formula: "C2H4",
	TMin:    298.15,
	TMax:    1500,
	Cp298:   5.325,
	A:       1.424,
	B:       14.394 * 1e-3,
	C:       -4.392 * 1e-6,
	D:       0 * 1e5,
}

var PropyleneGas = &HeatCapacity{
	Name:    "Propylene",
	Formula: "C3H6",
	TMin:    298.15,
	TMax:    1500,
	Cp298:   7.792,
	A:       1.637,
	B:       22.706 * 1e-3,
	C:       -6.915 * 1e-6,
	D:       0 * 1e5,
}

var OneButeneGas = &HeatCapacity{
	Name:    "1-Butene",
	Formula: "C4H8",
	TMin:    298.15,
	TMax:    1500,
	Cp298:   10.52,
	A:       1.967,
	B:       31.63 * 1e-3,
	C:       -9.873 * 1e-6,
	D:       0 * 1e5,
}

var OnePenteneGas = &HeatCapacity{
	Name:    "1-Pentene",
	Formula: "C5H10",
	TMin:    298.15,
	TMax:    1500,
	Cp298:   13.437,
	A:       2.691,
	B:       39.753 * 1e-3,
	C:       -12.447 * 1e-6,
	D:       0 * 1e5,
}

var OneHexeneGas = &HeatCapacity{
	Name:    "1-Hexene",
	Formula: "C6H12",
	TMin:    298.15,
	TMax:    1500,
	Cp298:   16.24,
	A:       3.22,
	B:       48.189 * 1e-3,
	C:       -15.157 * 1e-6,
	D:       0 * 1e5,
}

var OneHepteneGas = &HeatCapacity{
	Name:    "1-Heptene",
	Formula: "C7H14",
	TMin:    298.15,
	TMax:    1500,
	Cp298:   19.053,
	A:       3.768,
	B:       56.588 * 1e-3,
	C:       -17.847 * 1e-6,
	D:       0 * 1e5,
}

var OneOcteneGas = &HeatCapacity{
	Name:    "1-Octene",
	Formula: "C8H16",
	TMin:    298.15,
	TMax:    1500,
	Cp298:   21.868,
	A:       4.324,
	B:       64.96 * 1e-3,
	C:       -20.521 * 1e-6,
	D:       0 * 1e5,
}

var AcetaldehydeGas = &HeatCapacity{
	Name:    "Acetaldehyde",
	Formula: "C2H4O",
	TMin:    298.15,
	TMax:    1000,
	Cp298:   6.506,
	A:       1.693,
	B:       17.978 * 1e-3,
	C:       -6.158 * 1e-6,
	D:       0 * 1e5,
}

var AcetyleneGas = &HeatCapacity{
	Name:    "Acetylene",
	Formula: "C2H2",
	TMin:    298.15,
	TMax:    1500,
	Cp298:   5.253,
	A:       6.132,
	B:       1.952 * 1e-3,
	C:       0 * 1e-6,
	D:       -1.299 * 1e5,
}

var BenzeneGas = &HeatCapacity{
	Name:    "Benzene",
	Formula: "C6H6",
	TMin:    298.15,
	TMax:    1500,
	Cp298:   10.259,
	A:       -0.206,
	B:       39.064 * 1e-3,
	C:       -13.301 * 1e-6,
	D:       0 * 1e5,
}

var One3ButadieneGas = &HeatCapacity{
	Name:    "1,3-Butadiene",
	Formula: "C4H6",
	TMin:    298.15,
	TMax:    1500,
	Cp298:   10.72,
	A:       2.734,
	B:       26.786 * 1e-3,
	C:       -8.882 * 1e-6,
	D:       0 * 1e5,
}

var CyclohexaneGas = &HeatCapacity{
	Name:    "Cyclohexane",
	Formula: "C6H12",
	TMin:    298.15,
	TMax:    1500,
	Cp298:   13.121,
	A:       -3.876,
	B:       63.249 * 1e-3,
	C:       -20.928 * 1e-6,
	D:       0 * 1e5,
}

var EthanolGas = &HeatCapacity{
	Name:    "Ethanol",
	Formula: "C2H6O",
	TMin:    298.15,
	TMax:    1500,
	Cp298:   8.948,
	A:       3.518,
	B:       20.001 * 1e-3,
	C:       -6.002 * 1e-6,
	D:       0 * 1e5,
}

var EthylbenzeneGas = &HeatCapacity{
	Name:    "Ethylbenzene",
	Formula: "C8H10",
	TMin:    298.15,
	TMax:    1500,
	Cp298:   15.993,
	A:       1.124,
	B:       55.38 * 1e-3,
	C:       -18.476 * 1e-6,
	D:       0 * 1e5,
}

var EthyleneOxideGas = &HeatCapacity{
	Name:    "Ethylene oxide",
	Formula: "C2H4O",
	TMin:    298.15,
	TMax:    1000,
	Cp298:   5.784,
	A:       -0.385,
	B:       23.463 * 1e-3,
	C:       -9.296 * 1e-6,
	D:       0 * 1e5,
}

var FormaldehydeGas = &HeatCapacity{
	Name:    "Formaldehyde",
	Formula: "CH2O",
	TMin:    298.15,
	TMax:    1500,
	Cp298:   4.191,
	A:       2.264,
	B:       7.022 * 1e-3,
	C:       -1.877 * 1e-6,
	D:       0 * 1e5,
}

var MethanolGas = &HeatCapacity{
	Name:    "Methanol",
	Formula: "CH4O",
	TMin:    298.15,
	TMax:    1500,
	Cp298:   5.547,
	A:       2.211,
	B:       12.216 * 1e-3,
	C:       -3.45 * 1e-6,
	D:       0 * 1e5,
}

var StyreneGas = &HeatCapacity{
	Name:    "Styrene",
	Formula: "C8H8",
	TMin:    298.15,
	TMax:    1500,
	Cp298:   15.534,
	A:       2.05,
	B:       50.192 * 1e-3,
	C:       -16.662 * 1e-6,
	D:       0 * 1e5,
}

var TolueneGas = &HeatCapacity{
	Name:    "Toluene",
	Formula: "C7H8",
	TMin:    298.15,
	TMax:    1500,
	Cp298:   12.922,
	A:       0.29,
	B:       47.052 * 1e-3,
	C:       -15.716 * 1e-6,
	D:       0 * 1e5,
}

var AirGas = &HeatCapacity{
	Name:    "Air",
	Formula: "",
	TMin:    298.15,
	TMax:    2000,
	Cp298:   3.509,
	A:       3.355,
	B:       0.575 * 1e-3,
	C:       0 * 1e-6,
	D:       -0.016 * 1e5,
}

var AmmoniaGas = &HeatCapacity{
	Name:    "Ammonia",
	Formula: "NH",
	TMin:    298.15,
	TMax:    3,
	Cp298:   1800,
	A:       4.269,
	B:       3.578 * 1e-3,
	C:       3.02 * 1e-6,
	D:       0 * 1e5,
}

var BromineGas = &HeatCapacity{
	Name:    "Bromine",
	Formula: "Br2",
	TMin:    298.15,
	TMax:    3000,
	Cp298:   4.337,
	A:       4.493,
	B:       0.056 * 1e-3,
	C:       0 * 1e-6,
	D:       -0.154 * 1e5,
}

var CarbonMonoxideGas = &HeatCapacity{
	Name:    "Carbon monoxide",
	Formula: "CO",
	TMin:    298.15,
	TMax:    2500,
	Cp298:   3.507,
	A:       3.376,
	B:       0.557 * 1e-3,
	C:       0 * 1e-6,
	D:       -0.031 * 1e5,
}

var CarbonDioxideGas = &HeatCapacity{
	Name:    "Carbon dioxide",
	Formula: "CO2",
	TMin:    298.15,
	TMax:    2000,
	Cp298:   4.467,
	A:       5.457,
	B:       1.045 * 1e-3,
	C:       0 * 1e-6,
	D:       -1.157 * 1e5,
}

var CarbonDisulfideGas = &HeatCapacity{
	Name:    "Carbon disulfide",
	Formula: "CS2",
	TMin:    298.15,
	TMax:    1800,
	Cp298:   5.532,
	A:       6.311,
	B:       0.805 * 1e-3,
	C:       0 * 1e-6,
	D:       -0.906 * 1e5,
}

var ChlorineGas = &HeatCapacity{
	Name:    "Chlorine",
	Formula: "Cl2",
	TMin:    298.15,
	TMax:    3000,
	Cp298:   4.082,
	A:       4.442,
	B:       0.089 * 1e-3,
	C:       0 * 1e-6,
	D:       -0.344 * 1e5,
}

var HydrogenGas = &HeatCapacity{
	Name:    "Hydrogen",
	Formula: "H2",
	TMin:    298.15,
	TMax:    3000,
	Cp298:   3.468,
	A:       3.249,
	B:       0.422 * 1e-3,
	C:       0 * 1e-6,
	D:       0.083 * 1e5,
}

var HydrogenSulfideGas = &HeatCapacity{
	Name:    "Hydrogen sulfide",
	Formula: "H2S",
	TMin:    298.15,
	TMax:    2300,
	Cp298:   4.114,
	A:       3.931,
	B:       1.49 * 1e-3,
	C:       0 * 1e-6,
	D:       -0.232 * 1e5,
}

var HydrogenChlorideGas = &HeatCapacity{
	Name:    "Hydrogen chloride",
	Formula: "HCl",
	TMin:    298.15,
	TMax:    2000,
	Cp298:   3.512,
	A:       3.156,
	B:       0.623 * 1e-3,
	C:       0 * 1e-6,
	D:       0.151 * 1e5,
}

var HydrogenCyanideGas = &HeatCapacity{
	Name:    "Hydrogen cyanide",
	Formula: "HCN",
	TMin:    298.15,
	TMax:    2500,
	Cp298:   4.326,
	A:       4.736,
	B:       1.359 * 1e-3,
	C:       0 * 1e-6,
	D:       -0.725 * 1e5,
}

var NitrogenGas = &HeatCapacity{
	Name:    "Nitrogen",
	Formula: "N2",
	TMin:    298.15,
	TMax:    2000,
	Cp298:   3.502,
	A:       3.28,
	B:       0.593 * 1e-3,
	C:       0 * 1e-6,
	D:       0.04 * 1e5,
}

var NitrousOxideGas = &HeatCapacity{
	Name:    "Nitrous oxide",
	Formula: "N2O",
	TMin:    298.15,
	TMax:    2000,
	Cp298:   4.646,
	A:       5.328,
	B:       1.214 * 1e-3,
	C:       0 * 1e-6,
	D:       -0.928 * 1e5,
}

var NitricOxideGas = &HeatCapacity{
	Name:    "Nitric oxide",
	Formula: "NO",
	TMin:    298.15,
	TMax:    2000,
	Cp298:   3.59,
	A:       3.387,
	B:       0.629 * 1e-3,
	C:       0 * 1e-6,
	D:       0.014 * 1e5,
}

var NitrogenDioxideGas = &HeatCapacity{
	Name:    "Nitrogen dioxide",
	Formula: "NO",
	TMin:    298.15,
	TMax:    2,
	Cp298:   2000,
	A:       4.447,
	B:       4.982 * 1e-3,
	C:       1.195 * 1e-6,
	D:       0 * 1e5,
}

var DinitrogenTetroxideGas = &HeatCapacity{
	Name:    "Dinitrogen tetroxide",
	Formula: "N2O4",
	TMin:    298.15,
	TMax:    2000,
	Cp298:   9.198,
	A:       11.66,
	B:       2.257 * 1e-3,
	C:       0 * 1e-6,
	D:       -2.787 * 1e5,
}

var OxygenGas = &HeatCapacity{
	Name:    "Oxygen",
	Formula: "O2",
	TMin:    298.15,
	TMax:    2000,
	Cp298:   3.535,
	A:       3.639,
	B:       0.506 * 1e-3,
	C:       0 * 1e-6,
	D:       -0.227 * 1e5,
}

var SulfurDioxideGas = &HeatCapacity{
	Name:    "Sulfur dioxide",
	Formula: "SO2",
	TMin:    298.15,
	TMax:    2000,
	Cp298:   4.796,
	A:       5.699,
	B:       0.801 * 1e-3,
	C:       0 * 1e-6,
	D:       -1.015 * 1e5,
}

var SulfurTrioxideGas = &HeatCapacity{
	Name:    "Sulfur trioxide",
	Formula: "SO3",
	TMin:    298.15,
	TMax:    2000,
	Cp298:   6.094,
	A:       8.06,
	B:       1.056 * 1e-3,
	C:       0 * 1e-6,
	D:       -2.028 * 1e5,
}

var WaterGas = &HeatCapacity{
	Name:    "Water",
	Formula: "H2O",
	TMin:    298.15,
	TMax:    2000,
	Cp298:   4.038,
	A:       3.47,
	B:       1.45 * 1e-3,
	C:       0 * 1e-6,
	D:       0.121 * 1e5,
}

var AmmoniaLiquid = &HeatCapacity{
	Name:    "Ammonia",
	Formula: "",
	TMin:    273.15,
	TMax:    373.15,
	Cp298:   9.718,
	A:       22.626,
	B:       -100.75 * 1e-3,
	C:       192.71 * 1e-6,
	D:       0,
}

var AnilineLiquid = &HeatCapacity{
	Name:    "Aniline",
	Formula: "",
	TMin:    273.15,
	TMax:    373.15,
	Cp298:   23.07,
	A:       15.819,
	B:       29.03 * 1e-3,
	C:       -15.8 * 1e-6,
	D:       0,
}

var BenzeneLiquid = &HeatCapacity{
	Name:    "Benzene",
	Formula: "",
	TMin:    273.15,
	TMax:    373.15,
	Cp298:   16.157,
	A:       -0.747,
	B:       67.96 * 1e-3,
	C:       -37.78 * 1e-6,
	D:       0,
}

var One3ButadieneLiquid = &HeatCapacity{
	Name:    "1,3-Butadiene",
	Formula: "",
	TMin:    273.15,
	TMax:    373.15,
	Cp298:   14.779,
	A:       22.711,
	B:       -87.96 * 1e-3,
	C:       205.79 * 1e-6,
	D:       0,
}

var CarbonTetrachlorideLiquid = &HeatCapacity{
	Name:    "Carbon tetrachloride",
	Formula: "",
	TMin:    273.15,
	TMax:    373.15,
	Cp298:   15.751,
	A:       21.155,
	B:       -48.28 * 1e-3,
	C:       101.14 * 1e-6,
	D:       0,
}

var ChlorobenzeneLiquid = &HeatCapacity{
	Name:    "Chlorobenzene",
	Formula: "",
	TMin:    273.15,
	TMax:    373.15,
	Cp298:   18.24,
	A:       11.278,
	B:       32.86 * 1e-3,
	C:       -31.9 * 1e-6,
	D:       0,
}

var ChloroformLiquid = &HeatCapacity{
	Name:    "Chloroform",
	Formula: "",
	TMin:    273.15,
	TMax:    373.15,
	Cp298:   13.806,
	A:       19.215,
	B:       -42.89 * 1e-3,
	C:       83.01 * 1e-6,
	D:       0,
}

var CyclohexaneLiquid = &HeatCapacity{
	Name:    "Cyclohexane",
	Formula: "",
	TMin:    273.15,
	TMax:    373.15,
	Cp298:   18.737,
	A:       -9.048,
	B:       141.38 * 1e-3,
	C:       -161.62 * 1e-6,
	D:       0,
}

var EthanolLiquid = &HeatCapacity{
	Name:    "Ethanol",
	Formula: "",
	TMin:    273.15,
	TMax:    373.15,
	Cp298:   13.444,
	A:       33.866,
	B:       -172.6 * 1e-3,
	C:       349.17 * 1e-6,
	D:       0,
}

var EthyleneOxideLiquid = &HeatCapacity{
	Name:    "Ethylene oxide",
	Formula: "",
	TMin:    273.15,
	TMax:    373.15,
	Cp298:   10.59,
	A:       21.039,
	B:       -86.41 * 1e-3,
	C:       172.28 * 1e-6,
	D:       0,
}

var MethanolLiquid = &HeatCapacity{
	Name:    "Methanol",
	Formula: "",
	TMin:    273.15,
	TMax:    373.15,
	Cp298:   9.798,
	A:       13.431,
	B:       -51.28 * 1e-3,
	C:       131.13 * 1e-6,
	D:       0,
}

var NPropanolLiquid = &HeatCapacity{
	Name:    "n-Propanol",
	Formula: "",
	TMin:    273.15,
	TMax:    373.15,
	Cp298:   16.921,
	A:       41.653,
	B:       -210.32 * 1e-3,
	C:       427.2 * 1e-6,
	D:       0,
}

var SulfurTrioxideLiquid = &HeatCapacity{
	Name:    "Sulfur trioxide",
	Formula: "",
	TMin:    273.15,
	TMax:    373.15,
	Cp298:   30.408,
	A:       -2.93,
	B:       137.08 * 1e-3,
	C:       -84.73 * 1e-6,
	D:       0,
}

var TolueneLiquid = &HeatCapacity{
	Name:    "Toluene",
	Formula: "",
	TMin:    273.15,
	TMax:    373.15,
	Cp298:   18.611,
	A:       15.133,
	B:       6.79 * 1e-3,
	C:       16.35 * 1e-6,
	D:       0,
}

var WaterLiquid = &HeatCapacity{
	Name:    "Water",
	Formula: "",
	TMin:    273.15,
	TMax:    373.15,
	Cp298:   9.069,
	A:       8.712,
	B:       1.25 * 1e-3,
	C:       -0.18 * 1e-6,
	D:       0,
}

var CaOSolid = &HeatCapacity{
	Name:    "CaO",
	Formula: "",
	TMin:    298.15,
	TMax:    2000,
	Cp298:   5.058,
	A:       6.104,
	B:       0.443 * 1e-3,
	C:       0,
	D:       -1.047 * 1e5,
}

var CaCOSolid = &HeatCapacity{
	Name:    "CaCO",
	Formula: "",
	TMin:    298.15,
	TMax:    3,
	Cp298:   1200,
	A:       9.848,
	B:       12.572 * 1e-3,
	C:       0,
	D:       2.637 * 1e5,
}

var CaOHSolid = &HeatCapacity{
	Name:    "Ca(OH)",
	Formula: "",
	TMin:    298.15,
	TMax:    2,
	Cp298:   700,
	A:       11.217,
	B:       9.597 * 1e-3,
	C:       0,
	D:       5.435 * 1e5,
}

var CaCSolid = &HeatCapacity{
	Name:    "CaC",
	Formula: "",
	TMin:    298.15,
	TMax:    2,
	Cp298:   720,
	A:       7.508,
	B:       8.254 * 1e-3,
	C:       0,
	D:       1.429 * 1e5,
}

var CaClSolid = &HeatCapacity{
	Name:    "CaCl",
	Formula: "",
	TMin:    298.15,
	TMax:    2,
	Cp298:   1055,
	A:       8.762,
	B:       8.646 * 1e-3,
	C:       0,
	D:       1.53 * 1e5,
}

var CGraphiteSolid = &HeatCapacity{
	Name:    "C (graphite)",
	Formula: "",
	TMin:    298.15,
	TMax:    2000,
	Cp298:   1.026,
	A:       1.771,
	B:       0.771 * 1e-3,
	C:       0,
	D:       -0.867 * 1e5,
}

var CuSolid = &HeatCapacity{
	Name:    "Cu",
	Formula: "",
	TMin:    298.15,
	TMax:    1357,
	Cp298:   2.959,
	A:       2.677,
	B:       0.815 * 1e-3,
	C:       0,
	D:       0.035 * 1e5,
}

var CuOSolid = &HeatCapacity{
	Name:    "CuO",
	Formula: "",
	TMin:    298.15,
	TMax:    1400,
	Cp298:   5.087,
	A:       5.78,
	B:       0.973 * 1e-3,
	C:       0,
	D:       -0.874 * 1e5,
}

var FeSolid = &HeatCapacity{
	Name:    "Fe(α)",
	Formula: "",
	TMin:    298.15,
	TMax:    1043,
	Cp298:   3.005,
	A:       -0.111,
	B:       6.111 * 1e-3,
	C:       0,
	D:       1.15 * 1e5,
}

var Fe2O3Solid = &HeatCapacity{
	Name:    "Fe2O3",
	Formula: "",
	TMin:    298.15,
	TMax:    960,
	Cp298:   12.48,
	A:       11.812,
	B:       9.697 * 1e-3,
	C:       0,
	D:       -1.976 * 1e5,
}

var Fe3O4Solid = &HeatCapacity{
	Name:    "Fe3O4",
	Formula: "",
	TMin:    298.15,
	TMax:    850,
	Cp298:   18.138,
	A:       9.594,
	B:       27.112 * 1e-3,
	C:       0,
	D:       0.409 * 1e5,
}

var FeSSolid = &HeatCapacity{
	Name:    "FeS",
	Formula: "",
	TMin:    298.15,
	TMax:    411,
	Cp298:   6.573,
	A:       2.612,
	B:       13.286 * 1e-3,
	C:       0,
	D:       0 * 1e5,
}

var I2Solid = &HeatCapacity{
	Name:    "I2",
	Formula: "",
	TMin:    298.15,
	TMax:    386.8,
	Cp298:   6.929,
	A:       6.481,
	B:       1.502 * 1e-3,
	C:       0,
	D:       0 * 1e5,
}

var LiClSolid = &HeatCapacity{
	Name:    "LiCl",
	Formula: "",
	TMin:    298.15,
	TMax:    800,
	Cp298:   5.778,
	A:       5.257,
	B:       2.476 * 1e-3,
	C:       0,
	D:       -0.193 * 1e5,
}

var NH4ClSolid = &HeatCapacity{
	Name:    "NH 4Cl",
	Formula: "",
	TMin:    298.15,
	TMax:    458,
	Cp298:   10.741,
	A:       5.939,
	B:       16.105 * 1e-3,
	C:       0,
	D:       0 * 1e5,
}

var NaSolid = &HeatCapacity{
	Name:    "Na",
	Formula: "",
	TMin:    298.15,
	TMax:    371,
	Cp298:   3.386,
	A:       1.988,
	B:       4.688 * 1e-3,
	C:       0,
	D:       0 * 1e5,
}

var NaClSolid = &HeatCapacity{
	Name:    "NaCl",
	Formula: "",
	TMin:    298.15,
	TMax:    1073,
	Cp298:   6.111,
	A:       5.526,
	B:       1.963 * 1e-3,
	C:       0,
	D:       0 * 1e5,
}

var NaOHSolid = &HeatCapacity{
	Name:    "NaOH",
	Formula: "",
	TMin:    298.15,
	TMax:    566,
	Cp298:   7.177,
	A:       0.121,
	B:       16.316 * 1e-3,
	C:       0,
	D:       1.948 * 1e5,
}

var NaHCOSolid = &HeatCapacity{
	Name:    "NaHCO",
	Formula: "",
	TMin:    298.15,
	TMax:    3,
	Cp298:   400,
	A:       10.539,
	B:       5.128 * 1e-3,
	C:       0,
	D:       18.148 * 1e5,
}

var SRhombicSolid = &HeatCapacity{
	Name:    "S (rhombic)",
	Formula: "",
	TMin:    298.15,
	TMax:    368.3,
	Cp298:   3.748,
	A:       4.114,
	B:       -1.728 * 1e-3,
	C:       0,
	D:       -0.783 * 1e5,
}

var SiOSolid = &HeatCapacity{
	Name:    "SiO",
	Formula: "",
	TMin:    298.15,
	TMax:    2,
	Cp298:   0,
	A:       847,
	B:       5.345 * 1e-3,
	C:       0,
	D:       4.871 * 1e5,
}
